backend:
  name: github
  repo: adamavenir/sarahavenir.com
  branch: main

media_folder: static/images
public_folder: images

collections:
  - name: "blog"
    label: "Blog"
    label_singular: "blog post"
    folder: "content/blog"
    create: true
    slug: "slug"
    media_folder: "content/blog"
    path: "{{year}}/{{title}}"
    preview_path: "/{{year}}/{{title}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
        }
      - { name: image, label: Image, widget: image, required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    label_singular: "page"
    folder: "content/pages"
    create: true
    slug: "slug"
    media_folder: "content/pages"
    path: "{{title}}"
    preview_path: "{{title}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
        }
      - { name: image, label: Image, widget: image, required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "reading"
    label: "Reading"
    label_singular: "reading"
    folder: "content/reading"
    create: true
    slug: "slug"
    media_folder: "content/reading"
    path: "/reading/{{title}}"
    preview_path: "/reading/{{title}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - { label: "Date", name: "date", widget: "datetime" }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
        }
      - { name: image, label: Image, widget: image, required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
